clone_folder: c:\trik-runtime

environment:
  global:
    PYTHON_PATH: C:\Python36
    PYTHON_LIB: '%PYTHON_PATH%\libs'
    PROJECT_FILE: trikRuntime
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=3 -md=32m
    BUILD_DIR: '%APPVEYOR_BUILD_FOLDER%\.build'

  matrix:
      - MINGW: C:\Qt\Tools\mingw530_32
        QTDIR: C:\Qt\5.11\mingw53_32
      - MINGW: C:\Qt\Tools\mingw492_32
        QTDIR: C:\Qt\5.6\mingw49_32

configuration:
  - debug
  - release

cache:
  - '%BUILD_DIR%'
before_build:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_PATH%;%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PATH%
  - if not exist %BUILD_DIR% md %BUILD_DIR%
  - du -sh %BUILD_DIR%
  - pacman --verbose --noconfirm --sync ccache rsync curl
  - path
  - python -V
  - g++ --version
  - curl https://raw.githubusercontent.com/MestreLion/git-tools/master/git-restore-mtime-bare > .fix-mtime.py
  - python "%PYTHON_PATH%\Tools\scripts\2to3.py" -v -p -w -n -f all .fix-mtime.py
  - sed -ri "s#line.(startswith|split)\(#line.\1\(b#g" .fix-mtime.py
  - python .fix-mtime.py
  - git submodule foreach --recursive python %cd%\.fix-mtime.py

build_script:
  - cd %BUILD_DIR%
  - qmake %APPVEYOR_BUILD_FOLDER%\%PROJECT_FILE%.pro -spec win32-g++ CONFIG+=%CONFIGURATION%
  - mingw32-make -j2 qmake_all
  - mingw32-make -j2 all
  - qmake %APPVEYOR_BUILD_FOLDER%\tests\tests.pro -spec win32-g++ CONFIG+=%CONFIGURATION% -o tests.mak
  - mingw32-make -f tests.mak -j2 qmake_all
  - mingw32-make -f tests.mak -j2 all

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd bin\x86-%CONFIGURATION%
  - if %CONFIGURATION% == debug set CONFIGURATION_SUFFIX=-d
  - .\trikScriptRunnerTests%CONFIGURATION_SUFFIX%
  - .\trikCommunicatorTests%CONFIGURATION_SUFFIX%
  - .\trikKernelTests%CONFIGURATION_SUFFIX%

artifacts:
 - path: bin\x86-$(configuration)
   name: trikRuntime-win32-$(configuration)

notifications:
  - provider: Slack
    incoming_webhook:
      secure: QRFxYnwQHitjlrmGleW/IvNXUciFrbLfMfUWJZJKMd7C4G39APa9IkFMmNO129P7kjgCIRevlyisi7L2DX5WOS0tyvxt6rhiq+g7Dn2rz74=
